name: Testing Calculator

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
      - name: Build with Maven
        run: mvn clean package
      - name: Run Junit tests
        run: mvn test